- .gitignore
- build.gradle
- src/main/java/org/programmers/signalbuddy/SignalBuddyApplication.java
- src/main/java/org/programmers/signalbuddy/domain/basetime/BaseTimeEntity.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/Bookmark.java
- src/main/java/org/programmers/signalbuddy/domain/comment/Comment.java
- src/main/java/org/programmers/signalbuddy/domain/crossroad/Crossroad.java
- src/main/java/org/programmers/signalbuddy/domain/crossroad/repository/CrossroadRepository.java
- src/main/java/org/programmers/signalbuddy/domain/crossroad/service/CrossroadService.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/Feedback.java
- src/main/java/org/programmers/signalbuddy/domain/like/Like.java
- src/main/java/org/programmers/signalbuddy/domain/member/Member.java
- src/main/java/org/programmers/signalbuddy/domain/member/MemberStatus.java
- src/main/java/org/programmers/signalbuddy/domain/social/SocialProvider.java
- src/main/java/org/programmers/signalbuddy/global/config/JpaAuditingConfig.java
- src/main/java/org/programmers/signalbuddy/global/config/QuerydslConfig.java
- src/test/java/org/programmers/signalbuddy/SignalBuddyApplicationTests.java
- src/test/java/org/programmers/signalbuddy/domain/crossroad/service/CrossroadSaveTest.java
- src/test/resources/application-test.yml
> Querydsl 적용
> Mapstruct 적용  
> Hibernate-spatial 적용
> 엔티티 설계 및 관련 의존성 추가
> [feat] 엔티티 설계

- src/main/java/org/programmers/signalbuddy/domain/feedback/controller/FeedbackController.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/dto/FeedbackMapper.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/dto/FeedbackResponse.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/dto/FeedbackWriteRequest.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/entity/Feedback.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/exception/FeedbackErrorCode.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/service/FeedbackService.java
- src/main/java/org/programmers/signalbuddy/domain/member/exception/MemberErrorCode.java
- src/main/java/org/programmers/signalbuddy/global/exception/BusinessException.java
- src/main/java/org/programmers/signalbuddy/global/exception/ErrorCode.java
- src/main/java/org/programmers/signalbuddy/global/exception/GlobalErrorCode.java
- src/main/java/org/programmers/signalbuddy/global/exception/advice/GlobalExceptionHandler.java
- src/main/java/org/programmers/signalbuddy/global/exception/advice/dto/ErrorResponse.java
- src/test/java/org/programmers/signalbuddy/domain/crossroad/service/CrossroadSaveTest.java
- src/test/java/org/programmers/signalbuddy/domain/feedback/service/FeedbackServiceTest.java
- src/test/java/org/programmers/signalbuddy/global/support/ControllerTest.java
- src/test/java/org/programmers/signalbuddy/global/support/RepositoryTest.java
- src/test/java/org/programmers/signalbuddy/global/support/ServiceTest.java
> #5 
> 사용자가 피드백을 작성할 수 있는 기능을 구현
> global에 Exception 관련 기능들도 추가했어요. 이거 괜찮은지 확인 부탁드립니다!
> \+ 단위 테스트 하실 때 상속받아서 사용하실 수 있도록 test/global/support에 추상 클래스 생성했습니다!
> [feat] 피드백 작성

- build.gradle
- src/main/java/org/programmers/signalbuddy/domain/comment/controller/CommentController.java
- src/main/java/org/programmers/signalbuddy/domain/comment/dto/CommentRequest.java
- src/main/java/org/programmers/signalbuddy/domain/comment/entity/Comment.java
- src/main/java/org/programmers/signalbuddy/domain/comment/exception/CommentErrorCode.java
- src/main/java/org/programmers/signalbuddy/domain/comment/service/CommentService.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/dto/FeedbackWriteRequest.java
- src/test/java/org/programmers/signalbuddy/domain/comment/service/CommentServiceTest.java
> #14 
> 댓글 삭제 기능, QClass를 import 할 수 있게 설정
>
> [feature] 댓글 수정삭제

- src/main/java/org/programmers/signalbuddy/domain/comment/service/CommentService.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/controller/FeedbackController.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/entity/Feedback.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/exception/FeedbackErrorCode.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/service/FeedbackService.java
- src/test/java/org/programmers/signalbuddy/domain/feedback/service/FeedbackServiceTest.java
> [feature] 피드백 수정삭제

- src/main/java/org/programmers/signalbuddy/domain/comment/controller/CommentController.java
- src/main/java/org/programmers/signalbuddy/domain/comment/dto/CommentResponse.java
- src/main/java/org/programmers/signalbuddy/domain/comment/repository/CommentRepository.java
- src/main/java/org/programmers/signalbuddy/domain/comment/repository/CustomCommentRepository.java
- src/main/java/org/programmers/signalbuddy/domain/comment/repository/CustomCommentRepositoryImpl.java
- src/main/java/org/programmers/signalbuddy/domain/comment/service/CommentService.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/controller/FeedbackController.java
- src/test/java/org/programmers/signalbuddy/domain/comment/repository/CommentRepositoryTest.java
> #29 
> 특정 피드백의 댓글 목록을 조회하는 기능
>
> [feature] 게시물에 대한 댓글 목록 조회

- src/main/java/org/programmers/signalbuddy/domain/member/controller/MemberController.java
- src/main/java/org/programmers/signalbuddy/domain/member/service/AdminMemberService.java
> #27 
> 관리자 사용자 회원 상세 조회 기능 입니다.
> 여기에 작성
> [feat] 관리자 회원 상세 조회 기능 추가

- src/main/java/org/programmers/signalbuddy/domain/bookmark/controller/BookmarkController.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/dto/BookmarkRequest.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/entity/Bookmark.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/exception/BookmarkErrorCode.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/mapper/BookmarkMapper.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/repository/BookmarkRepositoryCustomImpl.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/service/BookmarkService.java
- src/main/java/org/programmers/signalbuddy/global/config/GeometryConfig.java
- src/main/java/org/programmers/signalbuddy/global/exception/advice/GlobalExceptionHandler.java
- src/test/java/org/programmers/signalbuddy/domain/bookmark/service/BookmarkServiceTest.java
> #23 즐겨찾기 등록/수정/삭제
> 즐겨찾기 CUD 기능 구현
> [feat] 즐겨찾기 등록 수정 삭제 기능 추가

- src/main/java/org/programmers/signalbuddy/domain/feedback/dto/FeedbackResponse.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/repository/CustomFeedbackRepository.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/repository/CustomFeedbackRepositoryImpl.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/service/FeedbackService.java
- src/main/java/org/programmers/signalbuddy/domain/member/controller/MemberController.java
- src/test/java/org/programmers/signalbuddy/domain/feedback/service/FeedbackServiceTest.java
> #38 마이페이지 피드백 모아 보기
> 마이페이지 피드백 목록 조회
> [feat] 마이페이지 피드백 목록 조회

- src/main/java/org/programmers/signalbuddy/domain/comment/repository/CustomCommentRepositoryImpl.java
- src/main/java/org/programmers/signalbuddy/domain/comment/service/CommentService.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/controller/FeedbackController.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/dto/FeedbackResponse.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/entity/AnswerStatus.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/entity/Feedback.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/entity/enums/AnswerStatus.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/repository/CustomFeedbackRepository.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/repository/CustomFeedbackRepositoryImpl.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/service/FeedbackService.java
- src/main/java/org/programmers/signalbuddy/domain/member/entity/Member.java
- src/main/java/org/programmers/signalbuddy/global/exception/advice/GlobalExceptionHandler.java
- src/main/java/org/programmers/signalbuddy/global/util/QueryDSLUtil.java
- src/test/java/org/programmers/signalbuddy/domain/comment/service/CommentServiceTest.java
- src/test/java/org/programmers/signalbuddy/domain/feedback/repository/FeedbackRepositoryTest.java
> #31 
> 관리자 피드백 조회 시, 각 컬럼별 정렬과 날짜 범위 지정 기능 추가
설정한 값대로 조건을 설정되고, 정렬까지 처리됨
>
> [feature] 관리자 피드백 목록 조회

- build.gradle
- src/main/java/org/programmers/signalbuddy/domain/feedback/controller/FeedbackController.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/repository/FeedbackJdbcRepository.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/service/FeedbackService.java
- src/main/java/org/programmers/signalbuddy/global/util/QueryDSLUtil.java
- src/test/java/org/programmers/signalbuddy/domain/feedback/repository/FeedbackJdbcRepositoryTest.java
> #43 
> full text search 쿼리로 관리자의 피드백 검색 기능 추가
> full text search의 경우 h2에서는 지원하지 않아 로컬 db로 테스트 했습니다.
> [feature] 관리자 피드백 검색 기능

- src/main/java/org/programmers/signalbuddy/domain/member/controller/MemberController.java
- src/main/java/org/programmers/signalbuddy/domain/member/dto/MemberJoinRequest.java
- src/main/java/org/programmers/signalbuddy/domain/member/exception/MemberErrorCode.java
- src/main/java/org/programmers/signalbuddy/domain/member/repository/MemberRepository.java
- src/main/java/org/programmers/signalbuddy/domain/member/service/MemberService.java
- src/test/java/org/programmers/signalbuddy/domain/member/service/MemberServiceTest.java
> #45 
> 회원 가입을 요청하는 회원의 정보를 db에 저장한다.
> 여기에 작성
> feat: SignalBuddy 제공 회원가입 기능 구현

- src/main/java/org/programmers/signalbuddy/global/config/RedisConfig.java
- src/test/java/org/programmers/signalbuddy/global/config/RedisConfigTest.java
> #50 
> redis 사용을 위한 redisConfig 파일 추가
> 여기에 작성
> [feat] RedisConfig 파일 추가

- src/test/java/org/programmers/signalbuddy/global/config/RedisConfig.java
- src/test/java/org/programmers/signalbuddy/global/config/RedisConfigTest.java
- src/test/java/org/programmers/signalbuddy/global/db/RedisTestContainer.java
> #59 
> Redis TestContainer를 생성하여, 테스트 코드 동작 시 사용
> Redis를 사용하는 테스트 코드를 작성하실 때, `RedisTestContainer` 인터페이스를 상속받으시면 됩니다.
> [feat] redis testcontainers로 등록

- src/main/java/org/programmers/signalbuddy/domain/feedback/controller/FeedbackWebController.java
- src/main/resources/static/css/feedback/list.css
- src/main/resources/templates/feedback/list.html
> #62 
> thymeleaf로 피드백 목록 페이지 렌더링
> css가 너무 복잡해서 디자인보다는 기능 위주로 작업했습니다
> [feat] 피드백 목록 페이지 프론트 작업

- src/main/java/org/programmers/signalbuddy/domain/feedback/controller/FeedbackWebController.java
- src/main/resources/static/css/feedback/info.css
- src/main/resources/templates/feedback/info.html
> #66
> 피드백 상세 페이지에서 피드백 내용과 관련 댓글 출력
>
> [feat] 피드백 상세 페이지 프론트 작업

- src/main/java/org/programmers/signalbuddy/domain/comment/repository/CustomCommentRepositoryImpl.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/controller/FeedbackWebController.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/dto/FeedbackWriteRequest.java
- src/main/java/org/programmers/signalbuddy/domain/member/repository/MemberRepository.java
- src/main/resources/static/css/feedback/write.css
- src/main/resources/templates/feedback/edit.html
- src/main/resources/templates/feedback/info.html
- src/main/resources/templates/feedback/list.html
- src/main/resources/templates/feedback/write.html
> #71 
> 피드백 생성, 수정, 삭제 작업 프론트에 연결
>
> [feat] 피드백 생성 수정 삭제 프론트 작업

- build.gradle
- src/main/java/org/programmers/signalbuddy/domain/member/controller/MemberWebController.java
- src/main/java/org/programmers/signalbuddy/domain/member/repository/MemberRepository.java
- src/main/java/org/programmers/signalbuddy/domain/member/service/MemberService.java
- src/main/java/org/programmers/signalbuddy/global/annotation/CurrentUser.java
- src/main/java/org/programmers/signalbuddy/global/config/RedisConfig.java
- src/main/java/org/programmers/signalbuddy/global/config/SecurityConfig.java
- src/main/java/org/programmers/signalbuddy/global/config/SessionConfig.java
- src/main/java/org/programmers/signalbuddy/global/dto/CustomUser2Member.java
- src/main/java/org/programmers/signalbuddy/global/security/CustomUserDetails.java
- src/main/java/org/programmers/signalbuddy/global/security/CustomUserDetailsService.java
- src/main/java/org/programmers/signalbuddy/global/security/filter/UserAuthenticationFilter.java
- src/main/java/org/programmers/signalbuddy/global/security/handler/CustomAuthenticationSuccessHandler.java
- src/main/resources/templates/member/loginform.html
- src/test/java/org/programmers/signalbuddy/global/security/AuthTest.java
- src/test/java/org/programmers/signalbuddy/global/security/LoginTest.java
> #63 
> 기본 세션 로그인 및 로그아웃 구현
> 현재 로그인한 사용자의 정보를 가져오는 어노테이션 구현
> 여기에 작성
> [feat] 기본 로그인 및 로그아웃 구현

- src/main/java/org/programmers/signalbuddy/domain/bookmark/controller/BookmarkController.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/controller/BookmarkWebController.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/dto/BookmarkResponse.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/entity/Bookmark.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/repository/BookmarkRepositoryCustomImpl.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/service/BookmarkService.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/repository/CustomFeedbackRepositoryImpl.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/service/FeedbackService.java
- src/main/java/org/programmers/signalbuddy/domain/member/controller/MemberController.java
- src/main/java/org/programmers/signalbuddy/domain/member/controller/MemberWebController.java
- src/main/java/org/programmers/signalbuddy/domain/member/entity/Member.java
- src/main/java/org/programmers/signalbuddy/domain/member/exception/MemberErrorCode.java
- src/main/java/org/programmers/signalbuddy/domain/member/service/MemberService.java
- src/main/java/org/programmers/signalbuddy/global/config/SecurityConfig.java
- src/main/resources/static/css/common/common.css
- src/main/resources/static/css/member/bookmarks.css
- src/main/resources/static/css/member/feedbacks.css
- src/main/resources/static/css/member/info.css
- src/main/resources/templates/fragments/sidebar.html
- src/main/resources/templates/member/bookmark/edit.html
- src/main/resources/templates/member/bookmark/list.html
- src/main/resources/templates/member/bookmarks.html
- src/main/resources/templates/member/edit.html
- src/main/resources/templates/member/feedback/list.html
- src/main/resources/templates/member/info.html
- src/test/java/org/programmers/signalbuddy/domain/feedback/service/FeedbackServiceTest.java
> #48 
> 마이페이지 프론트 작업
> 마이페이지 관련 API url 수정 작업
> 연휴동안 작업하면서 커밋 안 하다가 하니 파일들이 많이 쌓였습니다....
> [feat] 마이페이지 프론트 작업

- src/main/java/org/programmers/signalbuddy/domain/comment/controller/CommentController.java
- src/main/java/org/programmers/signalbuddy/domain/comment/service/CommentService.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/controller/FeedbackController.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/controller/FeedbackWebController.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/service/FeedbackService.java
- src/main/java/org/programmers/signalbuddy/domain/member/dto/MemberJoinRequest.java
- src/main/java/org/programmers/signalbuddy/domain/member/entity/Member.java
- src/main/java/org/programmers/signalbuddy/global/config/SecurityConfig.java
- src/main/java/org/programmers/signalbuddy/global/dto/CustomUser2Member.java
- src/main/java/org/programmers/signalbuddy/global/security/CustomUserDetails.java
- src/main/resources/templates/feedback/info.html
- src/main/resources/templates/feedback/list.html
- src/test/java/org/programmers/signalbuddy/domain/comment/service/CommentServiceTest.java
- src/test/java/org/programmers/signalbuddy/domain/feedback/service/FeedbackServiceTest.java
> #80 
> 피드백 및 댓글 데이터에 대한 로그인 상태 관리
> Security 버그 수정
> 로그인한 사용자의 피드백 및 댓글만 수정, 삭제 할 수 있도록 함
> [refactor] 로그인된 사용자 처리

- src/main/java/org/programmers/signalbuddy/domain/admin/controller/AdminController.java
- src/main/java/org/programmers/signalbuddy/domain/admin/controller/AdminWebController.java
- src/main/java/org/programmers/signalbuddy/domain/admin/dto/AdminJoinRequest.java
- src/main/java/org/programmers/signalbuddy/domain/admin/service/AdminService.java
- src/main/java/org/programmers/signalbuddy/global/config/SecurityConfig.java
- src/main/java/org/programmers/signalbuddy/global/security/CustomUserDetails.java
- src/main/java/org/programmers/signalbuddy/global/security/filter/UserAuthenticationFilter.java
- src/main/java/org/programmers/signalbuddy/global/security/handler/CustomAuthenticationSuccessHandler.java
- src/main/resources/templates/admin/loginform.html
> #73 
> 인가 경로 수정
> 관리자 로그인 임시 UI 생성
> 관리자 회원가입 기능 추가
> 관리자 로그인 후 리다이렉트 경로 설정
> 여기에 작성
> [feat] 관리자 로그인 기능 추가

- build.gradle
- src/main/java/org/programmers/signalbuddy/domain/social/repository/SocialProviderRepository.java
- src/main/java/org/programmers/signalbuddy/global/config/SecurityConfig.java
- src/main/java/org/programmers/signalbuddy/global/dto/CustomUser2Member.java
- src/main/java/org/programmers/signalbuddy/global/security/basic/CustomUserDetails.java
- src/main/java/org/programmers/signalbuddy/global/security/basic/CustomUserDetailsService.java
- src/main/java/org/programmers/signalbuddy/global/security/filter/UserAuthenticationFilter.java
- src/main/java/org/programmers/signalbuddy/global/security/handler/CustomAuthenticationSuccessHandler.java
- src/main/java/org/programmers/signalbuddy/global/security/oauth/CustomOAuth2User.java
- src/main/java/org/programmers/signalbuddy/global/security/oauth/CustomOAuth2UserService.java
- src/main/java/org/programmers/signalbuddy/global/security/oauth/response/GoogleResponse.java
- src/main/java/org/programmers/signalbuddy/global/security/oauth/response/KakaoResponse.java
- src/main/java/org/programmers/signalbuddy/global/security/oauth/response/NaverResponse.java
- src/main/java/org/programmers/signalbuddy/global/security/oauth/response/OAuth2Response.java
- src/main/resources/templates/member/loginform.html
- src/test/java/org/programmers/signalbuddy/domain/comment/service/CommentServiceTest.java
- src/test/java/org/programmers/signalbuddy/domain/feedback/service/FeedbackServiceTest.java
- src/test/java/org/programmers/signalbuddy/domain/like/service/LikeServiceTest.java
> #87
> 소셜 로그인 기능 추가(카카오, 네이버, 구글)
> 여기에 작성
> [feat] 소셜로그인 기능 추가

- src/main/java/org/programmers/signalbuddy/domain/bookmark/controller/BookmarkController.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/controller/BookmarkWebController.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/repository/BookmarkRepositoryCustomImpl.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/service/BookmarkService.java
- src/main/java/org/programmers/signalbuddy/domain/feedback/repository/CustomFeedbackRepositoryImpl.java
- src/main/java/org/programmers/signalbuddy/domain/member/controller/MemberWebController.java
- src/main/java/org/programmers/signalbuddy/domain/member/dto/MemberUpdateRequest.java
- src/main/java/org/programmers/signalbuddy/domain/member/entity/Member.java
- src/main/java/org/programmers/signalbuddy/domain/member/exception/MemberErrorCode.java
- src/main/java/org/programmers/signalbuddy/domain/member/service/MemberService.java
- src/main/java/org/programmers/signalbuddy/global/security/basic/CustomUserDetailsService.java
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/fragments/sidebar.html
- src/main/resources/templates/member/bookmark/edit.html
- src/main/resources/templates/member/bookmark/list.html
- src/main/resources/templates/member/edit.html
- src/main/resources/templates/member/feedback/list.html
- src/main/resources/templates/member/info.html
- src/test/java/org/programmers/signalbuddy/domain/bookmark/service/BookmarkServiceTest.java
> #83 
> User 객체 변경하고 @CurrentUser 사용으로 변경
> 탈퇴한 회원일 경우 로그인 시 어떻게 처리할지 고민 중입니다.....
> Refactor/#83 user 객체 변경

- src/main/java/org/programmers/signalbuddy/domain/feedback/repository/FeedbackRepository.java
- src/main/java/org/programmers/signalbuddy/domain/like/controller/LikeController.java
- src/main/java/org/programmers/signalbuddy/domain/like/repository/LikeRepository.java
- src/main/java/org/programmers/signalbuddy/domain/like/service/LikeService.java
- src/main/java/org/programmers/signalbuddy/domain/member/repository/MemberRepository.java
- src/main/java/org/programmers/signalbuddy/global/exception/GlobalErrorCode.java
> [Refactor] 좋아요 기능 코드 개선

- src/main/java/org/programmers/signalbuddy/global/security/oauth/CustomOAuth2User.java
> #94 
> CustomOAuth2User에서 getAuthority()에서 반환 시, 접두어 "ROLE_" 추가
>
> [fix] 소셜로그인 인가 버그 해결

- src/main/java/org/programmers/signalbuddy/domain/admin/controller/AdminWebController.java
- src/main/resources/static/css/admin/main.css
- src/main/resources/templates/admin/list.html
- src/main/resources/templates/admin/main.html
> #96 
> 관리자 메인 페이지 프론트 작업했습니다.
> 피드백 관리 버튼 연결 필요합니다!
> [feat] 관리자 메인페이지 프론트 작업

- src/main/java/org/programmers/signalbuddy/domain/admin/controller/AdminWebController.java
- src/main/resources/static/css/admin/detail.css
- src/main/resources/static/css/admin/withdrawal.css
- src/main/resources/templates/admin/detail.html
- src/main/resources/templates/admin/list.html
- src/main/resources/templates/admin/main.html
- src/main/resources/templates/admin/withdrawal.html
- src/main/resources/templates/fragments/adminHeader.html
> #99 
> 관리자 회원 정보 관리 페이지 프론트 수정했습니다.
> 현재 회원 정보에 관리자도 나오는 것에 대해 수정 예정입니다.
> [feat] 관리자 회원 관리 프론트 수정

- src/main/java/org/programmers/signalbuddy/domain/admin/controller/AdminWebController.java
- src/main/java/org/programmers/signalbuddy/domain/admin/service/AdminService.java
- src/main/java/org/programmers/signalbuddy/domain/member/repository/CustomMemberRepository.java
- src/main/java/org/programmers/signalbuddy/domain/member/repository/CustomMemberRepositoryImpl.java
- src/main/resources/static/css/admin/detail.css
- src/main/resources/static/css/admin/withdrawal.css
- src/main/resources/templates/admin/detail.html
- src/main/resources/templates/admin/list.html
- src/main/resources/templates/admin/main.html
- src/main/resources/templates/admin/withdrawal.html
- src/main/resources/templates/fragments/adminHeader.html
> #101 
> 전체 회원 조회 시 관리자도 조회 되는 상황 수정
> 여기에 작성
> [refactor] 관리자 회원관리 수정

- src/main/java/org/programmers/signalbuddy/domain/bookmark/controller/BookmarkWebController.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/dto/BookmarkRequest.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/entity/Bookmark.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/exception/BookmarkErrorCode.java
- src/main/java/org/programmers/signalbuddy/domain/bookmark/service/BookmarkService.java
- src/main/resources/static/css/member/bookmarks.css
- src/main/resources/static/js/member/bookmark/create.js
- src/main/resources/static/js/member/bookmark/update.js
- src/main/resources/templates/member/bookmark/add.html
- src/main/resources/templates/member/bookmark/list.html
> feat: 즐겨찾기 등록, 수정 기능 구현

- src/main/java/org/programmers/signalbuddy/domain/crossroad/dto/CrossroadApiResponse.java
- src/main/java/org/programmers/signalbuddy/domain/crossroad/dto/CrossroadStateApiResponse.java
- src/main/resources/templates/feedback/edit.html
- src/main/resources/templates/feedback/info.html
- src/main/resources/templates/feedback/write.html
> #110 
> 피드백 페이지 버튼 숨기기, 교차로 API DTO 오류 해결
>
> [refactor] 피드백 페이지 수정

- src/main/java/org/programmers/signalbuddy/domain/admin/controller/AdminWebController.java
- src/main/java/org/programmers/signalbuddy/domain/member/controller/MemberWebController.java
- src/main/java/org/programmers/signalbuddy/global/security/handler/CustomAuthenticationSuccessHandler.java
- src/main/java/org/programmers/signalbuddy/global/security/oauth/CustomOAuth2UserService.java
- src/main/resources/templates/admin/loginform.html
- src/main/resources/templates/member/loginform.html
- src/main/resources/templates/member/signup.html
> #111
> 로그인, 회원가입 시, 에러가 발생하면 alert 띄우도록 했습니다.
> 소셜 로그인 회원 가입 시, 기본 프로필 이미지가 나올 수 있도록 했습니다.
> 관리자 및 사용자 로그인 성공 후, 리다이렉트 경로 수정했습니다.
> 여기에 작성
> [fix] 계정 관련 버그 수정

- src/main/resources/static/js/member/bookmark/create.js
- src/main/resources/static/js/member/bookmark/update.js
- src/main/resources/templates/member/bookmark/add.html
- src/main/resources/templates/member/bookmark/edit.html
- #134 
> 즐겨찾기 등록 및 수정 페이지 Map 추가
> [feat] 즐겨찾기 등록 및 수정 페이지 Map, Marker 추가

- jenkins/main.jenkinsfile
- #136 
> 서브모듈에 있던 jenkinsfile을 root 경로에 디렉토리로 위치함
> CI/CD 작업은 버그가 많이 생길 거 같아서 제가 임의로 머지할게요...
> [Fix] jenkinsfile 문제

- jenkins/main.jenkinsfile
- #136
> git clone 시 submodule만 clone 되는 문제를 해결
>
> [fix] submodule만 git clone 되는 문제 해결

- jenkins/main.jenkinsfile
- src/test/java/org/programmers/signalbuddy/domain/like/batch/LikeJobConfigTest.java
- #140 
> Jenkins에서 배포 작업을 하고 성공 여부를 Slack으로 알려줌
+ 배치 작업 주기를 1분으로 늘림
> 배포 알림 코멘트는 간략하게 설정했는데, 더 추가할 내용이 있을까요?
> Feature/#140 배포 시 알림 기능

- build.gradle
- jenkins/main.jenkinsfile
- src/main/java/org/programmers/signalbuddy/global/config/SecurityConfig.java
- #146 
> blue-green 무중단 배포와 로드 밸런싱을 적용했습니다.
> 잘 실행되는지 직접 테스트 해봐야 합니다.
> [feat] 무중단 배포하기

- build.gradle
- src/main/java/org/programmers/signalbuddy/global/config/SecurityConfig.java
- #157 
> actuator의 health 엔드포인트를 추가했습니다.
>
> [fix] health check bug 수정
